import { GridColDef, GridValueGetterParams } from "@material-ui/data-grid";
import renderSelectInput from "../components/SelectInput";
import { minMax } from "./Helpers";

const updateStrikePoints = (params: GridValueGetterParams) => {
    const value: any = params.value;
    return minMax(value);
};

const BossColumns: GridColDef[] = [
    {
        field: "id",
        headerName: "ID",
        width: 50,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "firstName",
        headerName: "First name",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "lastName",
        headerName: "Last name",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "ssn",
        headerName: "SSN",
        type: "number",
        width: 90,
        headerAlign: "center",
        align: "center",
        disableColumnMenu: true,
    },
    {
        field: "phone_number",
        headerName: "Phone Number",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "last_logged",
        headerName: "Last Seen",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
        type: "dateTime",
    },

    {
        field: "weekly_hours",
        headerName: "Weekly Hours",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "performance",
        headerName: "Performance",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "rank",
        headerName: "Rank",
        width: 75,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
        editable: true,
        renderCell: renderSelectInput,
    },
    {
        field: "strike_points",
        headerName: "Strike Points",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
        editable: true,
        type: "number",
        valueGetter: updateStrikePoints,
    },
];

const EmployeeColumns: GridColDef[] = [
    {
        field: "id",
        headerName: "ID",
        width: 50,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "firstName",
        headerName: "First name",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "lastName",
        headerName: "Last name",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "ssn",
        headerName: "SSN",
        type: "number",
        width: 90,
        headerAlign: "center",
        align: "center",
        disableColumnMenu: true,
    },
    {
        field: "phone_number",
        headerName: "Phone Number",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "last_logged",
        headerName: "Last Seen",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
        type: "dateTime",
    },

    {
        field: "weekly_hours",
        headerName: "Weekly Hours",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "performance",
        headerName: "Performance",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "rank",
        headerName: "Rank",
        width: 75,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
    },
    {
        field: "strike_points",
        headerName: "Strike Points",
        width: 130,
        headerAlign: "center",
        align: "center",
        hideSortIcons: false,
        disableColumnMenu: true,
        type: "number",
    },
];

export { BossColumns, EmployeeColumns };
